# Generated by Django 4.2.5 on 2023-09-12 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 21, 45, 584167, tzinfo=datetime.timezone.utc)),
        ),
    ]
