# Generated by Django 4.2.5 on 2023-09-13 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_starting_bid_bids_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 9, 13, 25, 779191, tzinfo=datetime.timezone.utc)),
        ),
    ]
