# Generated by Django 4.2.5 on 2023-09-14 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_value_alter_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 10, 38, 29, 575732, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('listing', models.ManyToManyField(blank=True, related_name='listings', to='auctions.listing')),
            ],
        ),
    ]
