# Generated by Django 4.2.5 on 2023-09-14 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_time_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 15, 54, 5, 120149, tzinfo=datetime.timezone.utc)),
        ),
    ]
