# Generated by Django 4.2.5 on 2023-09-15 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_active_alter_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 8, 33, 14, 56138, tzinfo=datetime.timezone.utc)),
        ),
    ]
