# Generated by Django 4.2.5 on 2023-09-15 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_time_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 8, 55, 53, 344622, tzinfo=datetime.timezone.utc)),
        ),
    ]
